config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    collection do
      get 'scoreboard'
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resources :teams, only: [:index, :create, :destroy]
  resources :games, only:[:index, :create, :destroy]
  resources :picks
  resources :rounds, only:[:index]
  resources :statics, only:[:index]
  resources :team_round_results, only:[:create, :destroy]

  root to: 'statics#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :ensure_session_token
  before_save :downcase_email_remove_whitespace
  validates :email, :team_name, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  has_many :picks

  attr_reader :password

  def password=(password)
    @password = password.strip
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password.strip)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email.downcase.strip)
    return nil unless user

    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    save!
  end

  def <=>(user)
    self_score = self.score
    user_score = user.score

    if self_score == user_score
      return [1, -1].sample
    else
      (self_score <=> user_score) * -1
    end
  end

  def limit
    score / 2
  end

  def score
    return 2000 unless TeamRoundResult.any?
    ActiveRecord::Base.connection.select_all( <<-SQL
        SELECT
          SUM(picks.points *
          picks.multiplier * (
            CASE teams.seed
            WHEN 1
            THEN 1.5
            ELSE teams.seed END
            )
          ) AS points
        FROM
          team_round_results
        JOIN
          picks ON
            picks.team_id = team_round_results.team_id AND
            picks.round_id = team_round_results.round_id
        JOIN
          teams ON
            teams.id = team_round_results.team_id
        WHERE
          team_round_results.win = true AND
          picks.user_id = #{id} AND
          picks.round_id IN (
            SELECT
              rounds.id
            FROM
              rounds
            WHERE
              rounds.picks_end < '#{DateTime.now}'
            ORDER BY
              rounds.picks_end DESC
            LIMIT
              2
            )
      SQL
      )
      .first["points"]
      .to_i
  end

  def self.scores_by_user_by_round
    return 2000 unless TeamRoundResult.any?

    ActiveRecord::Base.connection.select_all( <<-SQL
      SELECT
        users.team_name,
        users.name,
        picks.round_id,
        SUM(picks.points *
        picks.multiplier *
        teams.seed *
        (
        CASE WHEN
            team_round_results.win = true
        THEN
            1
        ELSE
            0
        END)
        ) AS points
      FROM
        team_round_results
      JOIN
        picks ON
          picks.team_id = team_round_results.team_id AND
          picks.round_id = team_round_results.round_id
      JOIN
        teams ON
          teams.id = team_round_results.team_id
      JOIN
        users ON users.id = picks.user_id
      GROUP BY
        users.team_name, users.name, picks.round_id
      SQL
      )
  end


  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def downcase_email_remove_whitespace
    self.email = self.email.downcase.strip unless self.email.nil?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_unless_logged_out, only: [:new, :create]
  before_action :redirect_if_logged_out, only: [:show, :index]

  def index
    @users = User.all.sort
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to scoreboard_users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    past_rounds = Round.where("picks_end < ?", DateTime.now )
                        .pluck(:id)
                        .join(",")
    # @user_picks = [1]
    @user_picks = ActiveRecord::Base.connection.select_all(<<-SQL
      SELECT
        rounds.id,
        rounds.name AS round_name,
        teams.name,
        teams.seed,
        picks.points,
        picks.multiplier,
        (picks.points *
          (CASE teams.seed WHEN 1 THEN 1.5 ELSE teams.seed END) *
          (CASE team_round_results.win WHEN true THEN 1 ELSE 0 END) *
          picks.multiplier) as payout,
        team_round_results.win AS result
      FROM
        users
      LEFT JOIN
        picks ON picks.user_id = users.id
      JOIN
        teams ON teams.id = picks.team_id
      LEFT JOIN
        team_round_results ON (
        team_round_results.round_id = picks.round_id AND
        team_round_results.team_id = picks.team_id
        )
      JOIN
        rounds ON rounds.id = picks.round_id
      WHERE
        users.id  = #{@user.id} AND
        picks.round_id IN (#{past_rounds})
      SQL
      ).sort_by {|pick| pick["id"].to_i}
  end

  def scoreboard
    redirect_to users_url
    # @scoreboard = scores_by_user_by_round
    # @rounds = Round.all.sort
  end

  private
  def user_params
    params.require(:user).permit(:email, :team_name, :password, :name)
  end

  def scores_by_user_by_round
    ActiveRecord::Base.connection.select_all(<<-SQL
      SELECT
        users.id,
        users.team_name,
        users.name,
        picks.round_id,
        SUM(picks.points *
        picks.multiplier *
        teams.seed *
        (
        CASE WHEN
            team_round_results.win = true
        THEN
            1
        ELSE
            0
        END)
        ) AS points
      FROM
        team_round_results
      JOIN
        picks ON
          picks.team_id = team_round_results.team_id AND
          picks.round_id = team_round_results.round_id
      JOIN
        teams ON
          teams.id = team_round_results.team_id
      JOIN
        users ON users.id = picks.user_id
      GROUP BY
        users.id, users.team_name, users.name, picks.round_id
      SQL
      )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_scoreboard_row.html.erb
<!-- Process scoreboard query into array with subarrs for each user's results -->

<% # get all the usernames
  teams = []
    scoreboard.each do |row|
    teams << row["team_name"] + "##" + row["id"]
  end
  teams = teams.uniq.sort
 %>

<%  results_arr = [] %>
<%  teams.each do |team|
      team_results = [team]
      %w(1 2 3 4 5 6).each do |round|
        matched_row =
          scoreboard
          .find {|row| row["team_name"] == team.split("##")[0] && row["round_id"] == round}

        points = matched_row ? matched_row["points"].to_i : 0
        team_results << points
      end

      team_results << team_results[1..-1].inject(:+)
      results_arr << team_results
    end

  results_arr.sort_by! {|result| result[-1] * -1}
%>

<% results_arr.each do |row| %>
  <tr>
  <% row.each_with_index do |entry, idx| %>
    <td>
    <% if idx == 0 %>
      <% team_name = entry.split("##")[0]
         user_id = entry.split("##")[1] %>
      <b><%= link_to team_name, user_url(user_id) %></b>
    <% else %>
      <%= entry %>
    <% end %>
    </td>
  <% end %>
  </tr>
<% end %>

</table>

app/views/users/index.html.erb
  <table class="table table-striped">
    <tr>
      <th>Player</th>
      <th>Score</th>
    </tr>
      <% @users.each do |user| %>
        <tr>
          <td><strong><%= link_to user.team_name, user_url(user) %></strong>
              (<%= user.name %>)</td>
          <td><%= user.score %></td>
        </tr>
      <% end %>
    </table>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<form action="<%= users_url %>" method="POST">
  <%= auth_token %>
  <p>
    <label for="name">Your Name</label>
    <input type="text" name="user[name]" value="<%= @user.name %>" id="name">
  </p>
  <p>
    <label for="email">Email</label>
    <input type="email" name="user[email]" value="<%= @user.email %>" id="email">
  </p>
  <p>
    <label for="password">Password</label>
    <input type="password" name="user[password]" value="<%= @user.password %>" id="password">
  </p>
  <p>
    <label for="team_name">Team Name</label>
    <input type="text" name="user[team_name]" value="<%= @user.team_name %>" id="team_name">
  </p>
  <p>
    <input type="submit" value="Sign Up" id="sign_up">
  </p>
</form>

app/views/users/render_row.html.erb
<!-- Render scoreboard array -->
<% scoreboard_arr.sort_by! {|row| row.last * -1 } %>
<% scoreboard_arr.each do |user_row| %>
  <% user_row.each do |col| %>
    <% if col == user_row.first %>
      <tr>
        <td>
          <%= col.html_safe %>
        </td>
    <% elsif col == user_row.last %>
        <td>
          <%= col %>
        </td>
      </tr>
    <% else %>
      <td>
        <%= col %>
      </td>
    <% end %>
  <% end %>
<% end %>

app/views/users/scoreboard.html.erb
<table class="table table-striped">
  <tr>
    <th>
    </th>
    <% Round.all.sort.each do |round| %>
      <th>
        <%= round.name %>
      </th>
    <% end %>
    <th>
      Total
    </th>
  </tr>

  <%= render 'scoreboard_row', scoreboard: @scoreboard, rounds: @rounds %>
</table>

app/views/users/show.html.erb
<h1><%= @user.team_name %></h1>

<% @user_picks.each_with_index do |pick, idx| %>
  <% if pick == @user_picks.first || pick["id"] != @user_picks[idx-1]["id"]%>
    <br><br><b><%= pick["round_name"] %></b><br>
  <% end %>
  (<%= pick["seed"] %>) <%= pick["name"] %>, <%= pick["points"] %>
  <% if pick["multiplier"] == "2" %> <b>x2</b><% end %>
  <% if pick["result"] != nil %>
    <% if pick["result"] == "t"  %>
      (WIN, <%= pick["payout"] %>)
    <% else %>
      (LOSS)
    <% end %>
  <% end %>
  <br>
<% end %>