config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    collection do
      get 'scoreboard'
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resources :teams, only: [:index, :create, :destroy]
  resources :games, only:[:index, :create, :destroy]
  resources :picks
  resources :rounds, only:[:index]
  resources :statics, only:[:index]
  resources :team_round_results, only:[:create, :destroy]

  root to: 'statics#index'
end

app/views/shared/_errors.html.erb
<% if !flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
    <div class="alert alert-danger" role="alert"><%= error %></div>
  <% end %>
<% end %>

app/views/shared/_game.html.erb
<p>
    <strong><%= game.region %></strong><br>
    (<%= game.away_team.seed %>) <%= game.away_team.name %> VS. <br>
    (<%= game.home_team.seed %>) <%= game.home_team.name %>
</p>

app/views/shared/_nav.html.erb
<% if params[:controller] != 'statics' %>
  <% if logged_in? %>
    <p><img src="http://i.imgur.com/WWe6IMs.png" width="25" style="vertical-align: text-bottom;"> SSNCAABBP |
      <%= link_to "Scoreboard", scoreboard_users_url %> |
      <%= link_to "Add/Edit Picks", new_pick_url %> |
      <% if admin? %>
        <%= link_to "All Picks", picks_url %> |
        <%= link_to "Edit Teams", teams_url %> |
        <%= link_to "Edit Round Results", rounds_url %> |
      <% end %>
      <%= link_to "Log Out", session_url, method: :delete %></p>
  <% else %>
    <p><img src="http://i.imgur.com/WWe6IMs.png" width="25" style="vertical-align: text-bottom;"> SSNCAABBP |
    <%= link_to "Log In", new_session_url %> |
    <%= link_to "Sign Up", new_user_url %></p>
  <% end %>
<% end %>
<hr>