config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    collection do
      get 'scoreboard'
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resources :teams, only: [:index, :create, :destroy]
  resources :games, only:[:index, :create, :destroy]
  resources :picks
  resources :rounds, only:[:index]
  resources :statics, only:[:index]
  resources :team_round_results, only:[:create, :destroy]

  root to: 'statics#index'
end

app/models/pick.rb
class Pick < ActiveRecord::Base
  after_initialize :ensure_multiplier

  validates :user_id, :round_id, :team_id, :points, presence: true
  validates :points, numericality: {only_integer: true}
  validates :multiplier, inclusion: { in: [1, 2] }
  validate :bet_limit_half_total_points_per_round, :one_double_per_round, :one_bet_per_team_per_round

  belongs_to :user
  belongs_to :round
  belongs_to :team

  def self.user_picks_per_round(user, round)
    Pick.where(user_id: user.id).where(round_id: round.id).includes(:team)
  end

  def result
    TeamRoundResult.where(
      "round_id = ? AND team_id = ?",
      self.round_id,
      self.team_id
      )
  end

  private
  def bet_limit_half_total_points_per_round
    return unless points.is_a?(Integer)
    total_points_wagered_round = user.picks.where(round_id: round_id).sum(:points)
    limit = (user.score / 2)
    if total_points_wagered_round + points > limit
      errors[:pick] << ": You can only wager #{limit - total_points_wagered_round} more points in the #{round.name}"
    end
  end

  def pick_round_is_open
    unless pick.round.picks_open?
      errors[:pick] << ": No more picks for that round!"
    end
  end

  def one_double_per_round
    return if self.multiplier == 1
    if Pick.where(
        user_id: self.user_id,
        round_id: self.round_id,
        multiplier: 2).any?
      errors[:pick] << ": Only one double per round!"
    end
  end

  def one_bet_per_team_per_round
    if Pick.where(
        user_id: self.user_id,
        round_id: self.round_id,
        team_id: self.team_id).any?
      errors[:pick] << ": Already picked that team!"
    end
  end

  def ensure_multiplier
    self.multiplier ||= 1
  end

end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_action :redirect_if_logged_out
  before_action :redirect_if_picks_closed, except: [:index]
  before_action :redirect_unless_admin, only: [:index]

  def index
    @picks = Pick.all
              .includes(:user, :team, :round)
              .sort_by { |pick| [pick.round_id * -1, pick.user_id]}
  end

  def new
    @current_rounds = Round.where("picks_start < ?", DateTime.now)
                           .where("picks_end > ?", DateTime.now)

    no_loss_teams_query = <<-SQL
      id NOT IN (
        SELECT
          team_id
        FROM
          team_round_results
        WHERE
          win = false
          )
    SQL

    @teams = Team.where(no_loss_teams_query).sort_by { |team| team.name }

    @picks = current_user.picks.includes(:team)

    @current_and_past_rounds = Round.where("picks_start < ?", DateTime.now)

    if flash[:round]
      @last_pick_round_id = flash[:round].to_i
    else
      @last_pick_round_id = -1
    end
  end

  def create
    pick = Pick.new(pick_params)
    pick.user_id = current_user.id

    if pick.save
      flash[:round] = params[:pick][:round_id]
      redirect_to new_pick_url
    else
      flash[:errors] = pick.errors.full_messages
      redirect_to new_pick_url
    end
  end

  def destroy
    pick = Pick.find(params[:id])
    pick.destroy if pick.round.picks_open?
    redirect_to new_pick_url
  end

  private
  def pick_params
    params.require(:pick).permit(:team_id, :round_id, :points, :multiplier)
  end

  def redirect_to_new_picks
    redirect_to new_pick_url
  end
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/picks/_previous_picks.html.erb
<hr>

<% rounds.reverse_chron.each do |round| %>
  <p><strong><%= round.name %></strong>
  <% round_picks = @picks.select { |pick| pick.round_id == round.id } %>
  <% points_wagered = round_picks.inject(0) { |c, pick| c + pick.points } %>
  <em>(<%= points_wagered %> / <%= current_user.limit %> points wagered)</em></p>

  <% round_picks.each do |pick| %>
    <p>
      (<%= pick.team.seed %>)
      <%= pick.team.name %>
      <%= pick.points %>
      <%= " <b>x2</b>".html_safe if pick.multiplier == 2 %>
    <% if round.picks_open? %>
      <%= link_to "Delete", pick_url(pick), method: :delete %>
    <% end %>
    </p>
  <% end %>
  <% if round_picks.length == 0 %>
    <p><em>No picks... yet.</em></p>
  <% end %>
<% end %>

app/views/picks/index.html.erb
<% @picks.each_with_index do |pick, idx| %>
  <% if pick != @picks.first && pick.round_id != @picks[idx -1].round_id %>
    <hr>
  <% end %>
  <% if pick != @picks.first && pick.user_id != @picks[idx -1].user_id %>
    <br>
  <% end %>
  <p><%= pick.round.name %>,
    <%= pick.user.name %>,
    <%= pick.team.name %>,
    <%= pick.points %>
    <% if pick.multiplier == 2 %>
      <b>x2</b>
    <% end %>
  </p>
<% end %>

app/views/picks/new.html.erb
<% if @current_rounds.any? %>
  <form action="<%= picks_url %>" method="POST">
    <%= auth_token %>
    <p>
      <label for="Round">Round</label>
      <select name="pick[round_id]">
        <% @current_rounds.sort.each do |round| %>
        <option
          value="<%= round.id %>"
          <%= "selected" if @last_pick_round_id == round.id %>>
            <%= round.name %>
          </option>
        <% end %>
      </select>
    </p>
    <p>
      <label for="Round">Team</label>
      <select name="pick[team_id]">
        <% @teams.each do |team| %>
        <option value="<%= team.id %>"><%= team.name %> (<%= team.seed %>)</option>
        <% end %>
      </select>
    </p>
    <p>
      <label for="Round">Points</label>
      <input type="text" name="pick[points]">
    </p>
    <p>
      <label for="double">Daily Double?</label>
      <input type="checkbox" name="pick[multiplier]" value="2" id="double" >
    </p>

    <input type="submit" value="Add Pick">
  </form>
<% end %>

<%= render 'previous_picks', rounds: @current_and_past_rounds %>